sonar.projectKey=journaltrendanalyzer
sonar.projectName=journaltrendanalyzer
sonar.organization=se190510-softwaretestinglab
sonar.projectVersion=1.0

sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/build/**,**/.dart_tool/**,**/generated_plugin_registrant.*,**/generated_plugins.cmake
sonar.test.inclusions=test/**/*_test.dart
sonar.coverage.exclusions=**/*_test.dart
sonar.dart.lcov.reportPaths=coverage/lcov.info
